feat: Added imageData to productsNavbar
gliff-ai/audit pull request #176
Opened 2022-04-01 13:04 UTC by Kinukeo

## Description

Added imageName and imageUid to annotation session in order to allow dominate to request this information and display them in the productsNavbar

Don't forget to reference all other pull requests which are associated to this one below: e.g.

relates [gliff-ai/dominate#306](https://github.com/gliff-ai/dominate/issues/306)

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [x ] I have read the gliff.ai Contribution Guide.
- [x ] I have requested to **pull a branch** and not from main.
- [x ] I have checked all commit message styles match the requested structure.
- [x ] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have assigned **3 or less** reviewers.
- [x ] New and existing unit tests pass locally with my changes.
- [x ] My changes generate no new warnings.

2022-04-04 09:43 UTC, SilviaZeta commented on src/components/ProjectAuditTable.tsx
> +  setProductsNavbarImageData: (imageName: ImageData) => void;
Make this prop optional and set a default or change the PR's title to "feat!: Added..." to make it a breaking change?

2022-04-04 09:45 UTC, SilviaZeta requested changes

2022-04-04 09:45 UTC, SilviaZeta commented on src/components/ProjectAuditTable.tsx
> +  setProductsNavbarImageData: (imageName: ImageData) => void;
and perhaps also rename `imageName` as `imageData`?

2022-04-04 09:48 UTC, SilviaZeta requested changes

2022-04-04 09:48 UTC, SilviaZeta commented on src/components/ProjectAuditTable.tsx
> +  setProductsNavbarImageData: (imageName: ImageData) => void;
and perhaps rename `imageName` as `imageData`?

2022-04-11 10:24 UTC, SilviaZeta approved these changes

2022-04-11 13:42 UTC, ChasNelson1990 approved these changes

2022-04-13 10:32 UTC, merged